Jiajia/backend game
ilovecjj1127/ft_transcendence pull request #4
Opened 2024-12-24 11:48 UTC by ilovecjj1127

add games app:

1. game model
2. game views: create, join, detail, start, interrupt, cancel, list
3. serializers and services

2025-01-06 17:51 UTC, ILeXeIR requested changes
1. Delete serializer duplicates (GameJoinSerializer, GameCancelSerializer, GameStartSerializer, GameInterruptSerializer, GameEndSerializer). One is enough.
2. Add modified_at field in the Game model
3. Add protection in Game Create: user should be able only to create games where he is a player1.
4. Add type annotation for returned objects in services (“-> Game:”)
5. Add protection in services start_game() who can do that
6. Move get_object_or_404 in services instead of views
7. Delete GameUpdateView and GameInterruptView. Our inner logic will use appropriate services, not users through endpoints.

2025-01-13 18:51 UTC, ilovecjj1127 commented
1. change duplicate serializers to one GameActionSerializer
2. add modified_at attribute to Game class
3. change player1 to read_only in GameCreateSerializer for protection; start_game service for player1 and 2 only
5. get_object_or_404 in GameService class
6. delete Gameupdateview and GameinterruptView; add PendingGameListView, ReadyGameListView and GameStatisticsView

2025-01-14 16:57 UTC, ILeXeIR commented
1. Don't use wildcard ("*") in imports.
2. It's better to return interrupt_game and update_game services. We don't need endpoints for them, but services themself may be useful.
3. Add "modified_at" field in serializers too.
4. "/games/start" endpoint doesn't work.

2025-01-14 17:32 UTC, ilovecjj1127 commented
1. remove wildcard
2. return interrupt_game and update_game services
3. add modified_at in serializers
4. fix start_game service

2025-01-14 18:44 UTC, merged